DROP TABLE IF EXISTS "tablaprueba";

CREATE TABLE "tablaprueba" (
  id SERIAL PRIMARY KEY,
  a varchar(255),
  b varchar(255),
  c varchar(255),
  d integer,
  e boolean,
  f varchar(1)
);

INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Carr Ewing Miranda','Allerona','elit.fermentum.risus@facilisislorem.ca',19,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Pittman Schwartz Halee','Olivola','iaculis@litora.co.uk',27,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Stephens Chandler Adrian','Hulste','dui.quis@netuset.net',18,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Mcfadden Grant Isadora','Rüsselsheim','luctus@orci.ca',24,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Kramer Randolph Teegan','Völklingen','mollis.Phasellus@Aliquamgravidamauris.ca',29,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Suarez Lane Hu','Tiruvottiyur','mauris.ipsum.porta@mipede.org',30,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Green Brewer Norman','Vegreville','ligula@egetvenenatis.edu',22,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Nunez Griffith Norman','Bollnäs','Vivamus@magnaUttincidunt.net',21,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Yates Hansen Brielle','Leverkusen','Quisque.ornare.tortor@metusAenean.org',29,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Rojas Rosario Dahlia','Sapele','porta.elit@aliquet.net',20,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Bates Gallegos Eric','Mesa','molestie@Donecegestas.edu',30,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Levine Padilla Maya','Wals-Siezenheim','consectetuer.ipsum@velitPellentesque.edu',21,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Ramos Russo Stacy','Sint-Amandsberg','pede.Cum@felis.org',27,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Chan Willis Aquila','Spruce Grove','vitae.velit.egestas@varius.edu',25,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Weiss Hood Byron','San Bernardo','diam.luctus.lobortis@turpisnec.co.uk',20,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Alvarado Murray Patricia','Ambattur','neque@Proin.edu',21,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Horton Harmon Chiquita','Wilskerke','Donec.tempor@ipsumcursus.edu',26,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Santiago Medina Pandora','Heikruis','sit.amet@Inat.com',28,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Roberts Smith Gabriel','San Giovanni Suergiu','varius.ultrices.mauris@eumetusIn.com',20,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Erickson Summers Kylynn','Itabuna','eu@vulputate.ca',28,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Powell Curry Lester','Penna in Teverina','at@nuncQuisqueornare.org',18,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Osborn Patel Miranda','Venlo','sociis.natoque.penatibus@metus.edu',27,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Arnold Jarvis Kyle','Plymouth','Suspendisse.ac.metus@idmagna.ca',29,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Holland Parker Merrill','Deventer','magnis@semvitaealiquam.net',28,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Flores Welch Fritz','Criciúma','ipsum@hendreritidante.edu',30,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Schwartz Goodwin Ulla','Padre las Casas','in.tempus.eu@Cras.org',25,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Cooper West Nina','Marano Lagunare','eget@volutpatornarefacilisis.net',18,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Ellison Zimmerman Stacey','Jamshedpur','convallis.ligula.Donec@venenatislacus.ca',23,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Shannon Chavez Kiara','Pizzoferrato','eget@lectus.ca',19,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Hardin Holder Kevyn','Hines Creek','lacus.Nulla.tincidunt@Cras.org',25,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Dillon Gardner Anne','Trochu','et.lacinia.vitae@turpisvitae.edu',28,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('William Lindsay Daniel','Timkur','sollicitudin.orci.sem@Quisqueporttitor.co.uk',25,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Baldwin Livingston Chava','Couture-Saint-Germain','egestas@molestieintempus.edu',24,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Page Mcpherson Pascale','Llanidloes','eleifend.nec@nec.ca',28,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Fulton Sheppard Nissim','Montluçon','dolor.nonummy@elitNulla.ca',24,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Compton Petersen Jaquelyn','Kerkrade','urna.Vivamus@nibhPhasellusnulla.org',19,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Waller Carson Lyle','Smithers','tellus@maurisut.ca',20,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Cohen Robertson Kyra','Łomża','libero.est.congue@dui.org',29,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Garrett Rivera Hermione','Whitchurch-Stouffville','dui.Fusce.diam@justo.com',28,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Delacruz Koch Colt','Timaukel','rutrum@egestas.edu',20,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Hester Harding Rebecca','Akola','penatibus.et@ut.com',26,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Ortiz Meyers Kadeem','Beuzet','ornare.placerat@ultrices.edu',18,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Ball Mercado Alan','Lestizza','arcu.Aliquam.ultrices@elementum.ca',20,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Ward Armstrong Faith','Zignago','Nunc.mauris.elit@magnaa.co.uk',25,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Myers Bray Jameson','Pinkafeld','Curabitur.egestas@euismodetcommodo.com',25,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Melendez Gomez Maris','Stirling','Nulla@ultricesiaculisodio.edu',27,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Campbell Sanchez Kareem','Maple Creek','Aliquam@odio.edu',30,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Sharpe Barnett Forrest','Warspite','ipsum.cursus@magnaUt.edu',25,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Cox Rodriguez Brielle','Hertsberge','turpis.egestas@ullamcorpernislarcu.com',26,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Dunlap Vega Talon','Limón (Puerto Limón)','ut.odio@Integervulputate.edu',29,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Pratt Parrish Mary','Ville de Maniwaki','magna.Nam.ligula@consequat.edu',29,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Barnes Rollins Quinn','Bonnert','aliquam.iaculis@Aliquamnisl.ca',24,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Morales Wyatt Kyra','Futrono','nulla.magna@IncondimentumDonec.com',26,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Burnett Gross Teagan','Stony Plain','ullamcorper@lectusNullam.net',18,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Foreman Burris Xerxes','Grimsby','massa@NuncmaurisMorbi.com',26,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Acosta Witt Lawrence','Monteu Roero','sit.amet.luctus@mifelis.com',26,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Lynn Griffith Emily','Zerkegem','nisi@ultricesposuere.ca',21,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Luna Alford Elizabeth','Holyhead','mi@nisisemsemper.org',30,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Carrillo Rocha Helen','Quinchao','elit.Aliquam@etnetus.com',27,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Underwood Gallagher Axel','Colorado Springs','Quisque@acmattis.net',24,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Nelson Swanson Xantha','Shahjahanpur','commodo@Curabitur.com',20,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Curry Faulkner Ivory','Vejalpur','ornare.placerat@ipsumcursus.com',18,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Simmons Reynolds Ginger','Tokoroa','quis.arcu@augueidante.ca',20,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Lewis Morin Rachel','Wabamun','quis.massa.Mauris@Crasdictum.org',22,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Clay England Wesley','Ulloa (Barrial)','fames.ac.turpis@lectussitamet.net',19,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Burch King Hayfa','Vihari','mauris.Suspendisse.aliquet@primisinfaucibus.net',29,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('French Owens Hedy','Beveren','consequat.enim@vitaeerat.com',19,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Alston Hancock Kermit','Pamplona','nibh@senectus.com',26,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Church Burris Uriah','Brye','faucibus.leo.in@ametmetus.org',26,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Graham Washington Ezra','Bridgend','Nullam.scelerisque@sit.ca',21,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Ellis Allison Oprah','Cape Breton Island','sed.turpis.nec@porttitorinterdumSed.org',23,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Bowen Pate Bradley','Haguenau','cursus.et@in.org',21,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Whitfield Nichols Martha','Oromocto','nec.ligula@aclibero.org',26,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Cline Sweeney Quyn','Kelowna','non.luctus@ultricesiaculis.ca',24,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Aguilar Kane Justin','Benestare','imperdiet.nec@a.edu',18,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Mathis Hendricks Autumn','Aparecida de Goiânia','dui.nec.tempus@luctus.com',23,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Potter Morgan Bell','Aizwal','nec.leo.Morbi@nonummyultricies.co.uk',18,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Hunter Lynn Mohammad','Montreuil','lectus.pede.ultrices@sempererat.com',19,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Cooley Hanson Lucius','Tintange','vestibulum@duiCum.net',21,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('York Hobbs Lenore','Malbaie','tellus@lectus.net',28,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Bean Rosario Jade','Bhilai','at.auctor.ullamcorper@Donecegestas.edu',29,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Barrett Byers Valentine','Friedrichshafen','massa.Mauris@consectetuer.net',24,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Burns Briggs Callum','Covington','mattis.semper.dui@utnisi.net',29,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Beach Edwards Hedda','Ninhue','vulputate@blanditNamnulla.com',30,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Garrett Neal Illana','Chandrapur','leo.Morbi.neque@diamProin.com',29,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Simpson Osborne Kasper','Tavier','et.magnis@loremvehiculaet.edu',27,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Brady Merritt Dominic','Sint-Denijs-Westrem','luctus.aliquet@necanteMaecenas.org',20,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Macdonald Woodard Porter','Quilaco','eu@sitametnulla.org',23,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Holt Harrison Leandra','Oamaru','amet.metus@ornarelectus.org',24,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Gilliam Cline Arthur','Norman Wells','et.magnis.dis@vehiculaPellentesque.net',25,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Mcconnell Nielsen Dominic','New Orleans','Vivamus.sit.amet@enimnectempus.org',21,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Cleveland Noble Zia','Sint-Ulriks-Kapelle','iaculis.odio.Nam@id.co.uk',25,'true','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Poole Baird Michelle','Pastena','montes.nascetur.ridiculus@nisia.org',30,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Parrish Houston Dacey','Santo Stefano del Sole','aliquam.iaculis.lacus@posuerecubilia.com',26,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Campbell Maynard Brody','Estevan','aliquet.vel.vulputate@pellentesquetellus.ca',22,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Carlson West Stephen','Lautaro','in.faucibus@Maurisvel.co.uk',26,'true','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Aguirre Fulton Bevis','Ciplet','mauris.a@tellus.com',24,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Potter Nolan Carol','Gaithersburg','Cras@nibh.com',30,'false','m');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Hodges Russell August','Burntisland','ultrices.iaculis@elit.org',21,'false','f');
INSERT INTO "tablaprueba" (a,b,c,d,e,f) VALUES ('Brennan Walton Jeremy','Spoleto','dis@sapienmolestie.net',20,'true','f');
